import type { Category, Level } from './vocab'

// Additional vocabulary, appended after the core list so existing word IDs stay stable.
// Format: zh | English | Tiếng Việt
export const RAW_EXTRA: Record<Level, Partial<Record<Category, string[]>>> = {
  A1: {
    basics: [
      '这|This|Này / đây',
      '那|That|Kia / đó',
      '这里|Here|Ở đây',
      '那里|There|Ở đó',
      '有|To have|Có',
      '没有|To not have|Không có',
      '在|At / in|Ở / tại',
      '和|And / with|Và / với',
      '很|Very|Rất',
      '也|Also|Cũng',
      '都|All / both|Đều',
      '四|Four|Bốn',
      '五|Five|Năm',
      '六|Six|Sáu',
      '七|Seven|Bảy',
      '八|Eight|Tám',
      '九|Nine|Chín',
      '零|Zero|Số không',
      '千|Thousand|Nghìn',
      '万|Ten thousand|Vạn / mười nghìn',
      '年|Year|Năm',
      '月|Month|Tháng',
      '日|Day / sun|Ngày / mặt trời',
      '星期|Week|Tuần / thứ',
      '早上|Morning|Buổi sáng',
      '中午|Noon|Buổi trưa',
      '晚上|Evening|Buổi tối',
      '点|O’clock / point|Giờ / điểm',
      '分钟|Minute|Phút',
      '小时|Hour|Giờ (tiếng)',
      '多|Many / much|Nhiều',
      '少|Few / little|Ít',
      '新|New|Mới',
      '旧|Old (things)|Cũ',
      '快|Fast|Nhanh',
      '慢|Slow|Chậm',
      '早|Early|Sớm',
      '晚|Late|Muộn',
      '上|Up / on|Trên',
      '下|Down / under|Dưới',
      '左|Left|Trái',
      '右|Right|Phải',
      '前面|In front|Phía trước',
      '后面|Behind|Phía sau',
      '里面|Inside|Bên trong',
      '外面|Outside|Bên ngoài',
      '名字|Name|Tên',
      '叫|To be called|Gọi là / tên là',
      '几|How many|Mấy',
      '怎么|How|Thế nào / làm sao',
      '为什么|Why|Tại sao',
      '哪个|Which|Cái nào',
      '东西|Thing|Đồ vật',
      '时间|Time|Thời gian',
      '钱|Money|Tiền',
      '书|Book|Sách',
      '桌子|Table|Cái bàn',
      '椅子|Chair|Cái ghế',
      '门|Door|Cửa',
      '房间|Room|Phòng',
      '床|Bed|Giường',
      '杯子|Cup|Cái cốc',
      '狗|Dog|Con chó',
      '猫|Cat|Con mèo',
      '睡觉|To sleep|Đi ngủ',
      '起床|To get up|Thức dậy',
      '玩|To play|Chơi',
      '唱歌|To sing|Hát',
      '跳舞|To dance|Nhảy múa',
      '游泳|To swim|Bơi',
      '知道|To know|Biết',
      '会|Can / will|Biết (làm) / sẽ',
      '能|To be able to|Có thể',
      '要|To want / will|Muốn / cần',
      '给|To give|Cho / đưa',
      '找|To look for|Tìm',
      '等|To wait|Đợi',
      '买单|To pay the bill|Tính tiền',
    ],
    people: [
      '哥哥|Older brother|Anh trai',
      '姐姐|Older sister|Chị gái',
      '弟弟|Younger brother|Em trai',
      '妹妹|Younger sister|Em gái',
      '爷爷|Grandfather (paternal)|Ông nội',
      '奶奶|Grandmother (paternal)|Bà nội',
      '儿子|Son|Con trai',
      '女儿|Daughter|Con gái',
      '丈夫|Husband|Chồng',
      '妻子|Wife|Vợ',
      '男人|Man|Đàn ông',
      '女人|Woman|Phụ nữ',
      '先生|Mister / husband|Ông / ngài',
      '小姐|Miss|Cô / tiểu thư',
      '同学|Classmate|Bạn cùng lớp',
      '邻居|Neighbor|Hàng xóm',
      '人|Person|Người',
    ],
    food: [
      '牛奶|Milk|Sữa bò',
      '面包|Bread|Bánh mì',
      '鱼|Fish|Cá',
      '肉|Meat|Thịt',
      '鸡肉|Chicken|Thịt gà',
      '牛肉|Beef|Thịt bò',
      '猪肉|Pork|Thịt lợn',
      '水果|Fruit|Trái cây',
      '蔬菜|Vegetables|Rau củ',
      '香蕉|Banana|Chuối',
      '西瓜|Watermelon|Dưa hấu',
      '饺子|Dumplings|Sủi cảo',
      '包子|Steamed bun|Bánh bao',
      '汤|Soup|Canh / súp',
      '饭店|Restaurant|Nhà hàng',
      '早饭|Breakfast|Bữa sáng',
      '午饭|Lunch|Bữa trưa',
      '晚饭|Dinner|Bữa tối',
      '饿|Hungry|Đói',
      '渴|Thirsty|Khát',
      '甜|Sweet|Ngọt',
      '辣|Spicy|Cay',
    ],
    travel: [
      '车站|Station|Nhà ga / bến xe',
      '公共汽车|Bus|Xe buýt',
      '自行车|Bicycle|Xe đạp',
      '路|Road|Con đường',
      '走|To walk|Đi bộ',
      '坐|To sit / to ride|Ngồi / đi (xe)',
      '开车|To drive|Lái xe',
      '到|To arrive|Đến',
      '回|To return|Về',
      '北京|Beijing|Bắc Kinh',
      '上海|Shanghai|Thượng Hải',
      '远|Far|Xa',
      '近|Near|Gần',
    ],
    feelings: [
      '开心|Happy|Vui vẻ',
      '累|Tired|Mệt',
      '难过|Sad|Buồn',
      '怕|To fear|Sợ',
      '笑|To laugh / smile|Cười',
      '哭|To cry|Khóc',
    ],
    work: [
      '做|To do / make|Làm',
      '忙|Busy|Bận',
      '办公室|Office|Văn phòng',
      '上班|To go to work|Đi làm',
      '下班|To get off work|Tan làm',
    ],
    shopping: [
      '商店|Shop|Cửa hàng',
      '块|Yuan (spoken)|Đồng (tệ, khẩu ngữ)',
      '卖|To sell|Bán',
      '要多少|How many do you want|Lấy bao nhiêu',
    ],
    health: [
      '身体|Body / health|Cơ thể / sức khỏe',
      '眼睛|Eyes|Mắt',
      '手|Hand|Tay',
      '头|Head|Đầu',
      '脚|Foot|Chân (bàn chân)',
    ],
  },
  A2: {
    travel: [
      '旅游|To travel / tourism|Du lịch',
      '导游|Tour guide|Hướng dẫn viên',
      '门票|Admission ticket|Vé vào cửa',
      '博物馆|Museum|Bảo tàng',
      '公园|Park|Công viên',
      '海边|Seaside|Bờ biển',
      '山|Mountain|Núi',
      '河|River|Sông',
      '城市|City|Thành phố',
      '农村|Countryside|Nông thôn',
      '方向|Direction|Phương hướng',
      '附近|Nearby|Gần đây',
      '迷路|To get lost|Lạc đường',
      '换钱|To exchange money|Đổi tiền',
      '登机|To board a plane|Lên máy bay',
      '航班|Flight|Chuyến bay',
      '座位|Seat|Chỗ ngồi',
      '晚点|Delayed|Trễ giờ',
      '出发|To set off|Xuất phát',
      '照相|To take photos|Chụp ảnh',
    ],
    basics: [
      '已经|Already|Đã',
      '一直|All along|Luôn luôn / suốt',
      '经常|Often|Thường xuyên',
      '有时候|Sometimes|Đôi khi',
      '总是|Always|Lúc nào cũng',
      '突然|Suddenly|Đột nhiên',
      '当然|Of course|Đương nhiên',
      '其实|Actually|Thật ra',
      '可能|Maybe|Có thể',
      '应该|Should|Nên',
      '必须|Must|Phải',
      '一定|Certainly|Nhất định',
      '如果|If|Nếu',
      '虽然|Although|Mặc dù',
      '但是|But|Nhưng',
      '因为|Because|Bởi vì',
      '所以|So / therefore|Cho nên',
      '然后|Then|Sau đó',
      '或者|Or|Hoặc',
      '还是|Or (in questions)|Hay là',
      '春天|Spring|Mùa xuân',
      '夏天|Summer|Mùa hè',
      '秋天|Autumn|Mùa thu',
      '冬天|Winter|Mùa đông',
    ],
    work: [
      '经理|Manager|Giám đốc / quản lý',
      '老板|Boss|Ông chủ',
      '员工|Employee|Nhân viên',
      '会议|Meeting|Cuộc họp',
      '加班|To work overtime|Tăng ca',
      '请假|To ask for leave|Xin nghỉ phép',
      '报告|Report|Báo cáo',
      '客户|Client|Khách hàng',
      '出差|Business trip|Đi công tác',
      '任务|Task|Nhiệm vụ',
    ],
    tech: [
      '上网|To go online|Lên mạng',
      '邮件|Email|Thư điện tử',
      '照片|Photo|Bức ảnh',
      '视频|Video|Video',
      '应用|App|Ứng dụng',
      '充电|To charge|Sạc pin',
      '屏幕|Screen|Màn hình',
      '键盘|Keyboard|Bàn phím',
      '微信|WeChat|WeChat',
      '发短信|To text|Nhắn tin',
    ],
    health: [
      '感冒|Cold (illness)|Cảm cúm',
      '发烧|Fever|Sốt',
      '咳嗽|Cough|Ho',
      '牙疼|Toothache|Đau răng',
      '肚子|Stomach|Bụng',
      '检查|To check / exam|Kiểm tra',
      '护士|Nurse|Y tá',
      '打针|Injection|Tiêm',
      '舒服|Comfortable|Dễ chịu',
      '受伤|To get injured|Bị thương',
    ],
    shopping: [
      '打折|Discount|Giảm giá',
      '付钱|To pay|Trả tiền',
      '现金|Cash|Tiền mặt',
      '信用卡|Credit card|Thẻ tín dụng',
      '收据|Receipt|Hóa đơn',
      '尺寸|Size|Kích cỡ',
      '试穿|To try on|Mặc thử',
      '退货|To return goods|Trả hàng',
      '排队|To queue|Xếp hàng',
      '价格|Price|Giá cả',
    ],
    feelings: [
      '紧张|Nervous|Căng thẳng / hồi hộp',
      '生气|Angry|Tức giận',
      '着急|Anxious / in a hurry|Sốt ruột',
      '害怕|Afraid|Sợ hãi',
      '兴奋|Excited|Hào hứng',
      '无聊|Bored|Chán',
      '孤单|Lonely|Cô đơn',
      '感动|Moved|Cảm động',
      '后悔|To regret|Hối hận',
      '骄傲|Proud|Tự hào',
    ],
    people: [
      '叔叔|Uncle|Chú',
      '阿姨|Aunt|Cô / dì',
      '男朋友|Boyfriend|Bạn trai',
      '女朋友|Girlfriend|Bạn gái',
      '客人|Guest|Khách',
      '司机|Driver|Tài xế',
      '服务员|Waiter|Nhân viên phục vụ',
      '警察|Police officer|Cảnh sát',
      '律师|Lawyer|Luật sư',
      '记者|Journalist|Nhà báo',
    ],
    food: [
      '菜单|Menu|Thực đơn',
      '点菜|To order food|Gọi món',
      '筷子|Chopsticks|Đũa',
      '盘子|Plate|Cái đĩa',
      '碗|Bowl|Cái bát',
      '饮料|Drink|Đồ uống',
      '啤酒|Beer|Bia',
      '果汁|Juice|Nước ép',
      '味道|Taste|Mùi vị',
      '咸|Salty|Mặn',
      '酸|Sour|Chua',
      '苦|Bitter|Đắng',
    ],
  },
  B1: {
    society: [
      '新闻|News|Tin tức',
      '政府|Government|Chính phủ',
      '法律|Law|Pháp luật',
      '教育|Education|Giáo dục',
      '人口|Population|Dân số',
      '交通|Traffic|Giao thông',
      '污染|Pollution|Ô nhiễm',
      '垃圾|Garbage|Rác',
      '回收|To recycle|Tái chế',
      '志愿者|Volunteer|Tình nguyện viên',
      '节日|Festival|Ngày lễ',
      '春节|Spring Festival|Tết Nguyên đán',
      '中秋节|Mid-Autumn Festival|Tết Trung thu',
      '民族|Ethnic group|Dân tộc',
      '城市化|Urbanization|Đô thị hóa',
    ],
    work: [
      '职业|Profession|Nghề nghiệp',
      '专业|Major / professional|Chuyên ngành',
      '能力|Ability|Năng lực',
      '经历|Experience (lived)|Trải nghiệm',
      '升职|Promotion|Thăng chức',
      '辞职|To resign|Từ chức / nghỉ việc',
      '招聘|To recruit|Tuyển dụng',
      '培训|Training|Đào tạo',
      '项目|Project|Dự án',
      '截止日期|Deadline|Hạn chót',
      '结果|Result|Kết quả',
      '管理|To manage|Quản lý',
      '负责|To be responsible|Chịu trách nhiệm',
      '安排|To arrange|Sắp xếp',
      '效果|Effect|Hiệu quả',
    ],
    feelings: [
      '感觉|Feeling|Cảm giác',
      '心情|Mood|Tâm trạng',
      '情绪|Emotion|Cảm xúc',
      '自信|Confident|Tự tin',
      '害羞|Shy|Xấu hổ / ngại ngùng',
      '好奇|Curious|Tò mò',
      '耐心|Patience|Kiên nhẫn',
      '羡慕|To envy (admiringly)|Ngưỡng mộ',
      '怀念|To miss / reminisce|Hoài niệm',
      '激动|Agitated / thrilled|Xúc động',
      '遗憾|Regret / pity|Tiếc nuối',
    ],
    basics: [
      '关于|About|Về',
      '根据|According to|Căn cứ vào',
      '通过|Through / by means of|Thông qua',
      '由于|Due to|Do / bởi vì',
      '而且|Moreover|Hơn nữa',
      '不但|Not only|Không những',
      '尽管|Even though|Cho dù / mặc dù',
      '除了|Except / besides|Ngoài ra / trừ',
      '只要|As long as|Chỉ cần',
      '只有|Only if|Chỉ có',
      '于是|Thereupon|Thế là',
      '否则|Otherwise|Nếu không thì',
      '甚至|Even|Thậm chí',
      '难道|Could it be that|Lẽ nào',
    ],
    health: [
      '过敏|Allergy|Dị ứng',
      '减肥|To lose weight|Giảm cân',
      '饮食|Diet|Ăn uống',
      '心理|Psychology|Tâm lý',
      '症状|Symptom|Triệu chứng',
      '治疗|Treatment|Điều trị',
      '手术|Surgery|Phẫu thuật',
      '保险|Insurance|Bảo hiểm',
    ],
    tech: [
      '程序|Program|Chương trình',
      '网站|Website|Trang web',
      '搜索|To search|Tìm kiếm',
      '浏览器|Browser|Trình duyệt',
      '账号|Account|Tài khoản',
      '登录|To log in|Đăng nhập',
      '注册|To register|Đăng ký',
      '更新|To update|Cập nhật',
      '系统|System|Hệ thống',
      '设备|Device|Thiết bị',
    ],
    travel: [
      '行程|Itinerary|Lịch trình',
      '退房|To check out|Trả phòng',
      '入住|To check in|Nhận phòng',
      '押金|Deposit|Tiền đặt cọc',
      '风景|Scenery|Phong cảnh',
      '当地|Local|Địa phương',
      '导航|Navigation|Chỉ đường',
    ],
    shopping: [
      '质量|Quality|Chất lượng',
      '品牌|Brand|Thương hiệu',
      '优惠|Discount / offer|Ưu đãi',
      '快递|Express delivery|Chuyển phát nhanh',
      '网购|Online shopping|Mua sắm trực tuyến',
      '订单|Order|Đơn hàng',
      '发货|To ship goods|Giao hàng',
    ],
  },
  B2: {
    work: [
      '绩效|Performance (KPI)|Hiệu suất công việc',
      '晋升|To be promoted|Thăng tiến',
      '跳槽|To change jobs|Nhảy việc',
      '领导|Leader|Lãnh đạo',
      '部门|Department|Bộ phận',
      '企业|Enterprise|Doanh nghiệp',
      '营销|Marketing|Tiếp thị',
      '销售|Sales|Bán hàng',
      '股票|Stock|Cổ phiếu',
      '股东|Shareholder|Cổ đông',
      '收入|Income|Thu nhập',
      '支出|Expenditure|Chi tiêu',
      '成本|Cost|Chi phí',
      '盈利|Profit / to profit|Lợi nhuận / có lãi',
      '亏损|Loss|Thua lỗ',
      '贷款|Loan|Khoản vay',
      '利率|Interest rate|Lãi suất',
      '汇率|Exchange rate|Tỷ giá',
    ],
    tech: [
      '区块链|Blockchain|Chuỗi khối',
      '云计算|Cloud computing|Điện toán đám mây',
      '大数据|Big data|Dữ liệu lớn',
      '机器学习|Machine learning|Học máy',
      '网络安全|Cybersecurity|An ninh mạng',
      '服务器|Server|Máy chủ',
      '数据库|Database|Cơ sở dữ liệu',
      '编程|Programming|Lập trình',
      '开发者|Developer|Nhà phát triển',
      '用户体验|User experience|Trải nghiệm người dùng',
      '界面|Interface|Giao diện',
      '漏洞|Vulnerability / bug|Lỗ hổng',
    ],
    society: [
      '政策|Policy|Chính sách',
      '改革|Reform|Cải cách',
      '制度|System / institution|Chế độ',
      '舆论|Public opinion|Dư luận',
      '媒体|Media|Truyền thông',
      '贫困|Poverty|Nghèo đói',
      '就业|Employment|Việc làm',
      '失业|Unemployment|Thất nghiệp',
      '老龄化|Aging (population)|Già hóa dân số',
      '移民|Immigration|Di cư',
      '歧视|Discrimination|Phân biệt đối xử',
      '平等|Equality|Bình đẳng',
      '福利|Welfare|Phúc lợi',
      '海关|Customs|Hải quan',
    ],
    basics: [
      '显然|Obviously|Rõ ràng',
      '毕竟|After all|Suy cho cùng',
      '何况|Let alone|Huống hồ',
      '总之|In short|Tóm lại',
      '相反|On the contrary|Ngược lại',
      '因此|Therefore|Vì vậy',
      '从而|Thereby|Từ đó',
      '以便|So that|Để tiện cho',
      '难免|Hard to avoid|Khó tránh khỏi',
      '未必|Not necessarily|Chưa chắc',
    ],
    feelings: [
      '焦虑|Anxious|Lo âu',
      '沮丧|Depressed / dejected|Chán nản',
      '欣慰|Gratified|Vui mừng an lòng',
      '愤怒|Fury|Phẫn nộ',
      '内疚|Guilty|Áy náy',
      '嫉妒|Jealous|Ghen tị',
      '委屈|Wronged|Tủi thân',
    ],
    health: [
      '免疫力|Immunity|Khả năng miễn dịch',
      '疫苗|Vaccine|Vắc-xin',
      '慢性病|Chronic disease|Bệnh mãn tính',
      '康复|Recovery|Hồi phục',
    ],
    shopping: [
      '性价比|Value for money|Đáng đồng tiền',
      '消费者|Consumer|Người tiêu dùng',
      '消费|Consumption|Tiêu dùng',
    ],
  },
  C1: {
    society: [
      '意识形态|Ideology|Hệ tư tưởng',
      '话语权|Right to speak / discourse power|Quyền phát ngôn',
      '城乡差距|Urban-rural gap|Chênh lệch thành thị nông thôn',
      '社会保障|Social security|An sinh xã hội',
      '公共利益|Public interest|Lợi ích công cộng',
      '文化认同|Cultural identity|Bản sắc văn hóa',
      '价值观|Values|Giá trị quan',
      '法治|Rule of law|Pháp trị',
      '腐败|Corruption|Tham nhũng',
      '弱势群体|Vulnerable groups|Nhóm yếu thế',
    ],
    basics: [
      '鉴于|In view of|Xét thấy',
      '综上所述|To sum up|Tóm lại những điều trên',
      '换言之|In other words|Nói cách khác',
      '不言而喻|Self-evident|Không cần nói cũng rõ',
      '截然不同|Completely different|Hoàn toàn khác nhau',
      '迄今为止|So far|Cho đến nay',
      '归根结底|In the final analysis|Xét cho cùng',
      '与此同时|At the same time|Đồng thời',
    ],
    work: [
      '可行性|Feasibility|Tính khả thi',
      '方案|Proposal / plan|Phương án',
      '规划|Planning|Quy hoạch',
      '统筹|Overall planning|Điều phối tổng thể',
      '执行力|Execution ability|Năng lực thực thi',
      '资源配置|Resource allocation|Phân bổ nguồn lực',
      '核心竞争力|Core competitiveness|Năng lực cạnh tranh cốt lõi',
      '瓶颈|Bottleneck|Nút thắt cổ chai',
      '转型|Transformation|Chuyển đổi',
    ],
    feelings: [
      '惆怅|Melancholy|Buồn man mác',
      '释然|Relieved|Nhẹ nhõm',
      '忐忑|Uneasy|Thấp thỏm',
      '感慨|To sigh with emotion|Cảm khái',
    ],
    tech: [
      '数字化|Digitalization|Số hóa',
      '智能化|Intelligent / smart (process)|Thông minh hóa',
      '生态系统|Ecosystem|Hệ sinh thái',
    ],
    health: [
      '亚健康|Sub-health|Tình trạng cận bệnh',
      '心理健康|Mental health|Sức khỏe tâm thần',
      '预防|Prevention|Phòng ngừa',
      '养生|Health preservation|Dưỡng sinh',
    ],
    travel: [
      '背包客|Backpacker|Dân du lịch bụi',
      '自由行|Independent travel|Du lịch tự túc',
      '深度游|In-depth travel|Du lịch trải nghiệm sâu',
    ],
    shopping: [
      '冲动消费|Impulse buying|Mua sắm bốc đồng',
      '理性消费|Rational spending|Tiêu dùng lý trí',
      '奢侈品|Luxury goods|Hàng xa xỉ',
    ],
    people: [
      '同龄人|Peers|Người cùng trang lứa',
      '合伙人|Business partner|Đối tác',
      '继承人|Heir|Người thừa kế',
      '知己|Close confidant|Tri kỷ',
      '前辈|Senior / predecessor|Tiền bối',
      '晚辈|Junior|Hậu bối',
    ],
  },
  Native: {
    idiom: [
      '自相矛盾|To contradict oneself|Tự mâu thuẫn',
      '刻舟求剑|To act without regard to change|Khắc thuyền tìm kiếm',
      '拔苗助长|To spoil things through haste|Nóng vội hỏng việc',
      '杞人忧天|Needless worry|Lo bò trắng răng',
      '狐假虎威|To bully using another’s power|Cáo mượn oai hùm',
      '卧虎藏龙|Hidden talents|Ngọa hổ tàng long',
      '名列前茅|To be among the best|Đứng đầu danh sách',
      '千方百计|By every possible means|Trăm phương nghìn kế',
      '一针见血|To hit the nail on the head|Nói trúng tim đen',
      '七上八下|Anxious, on tenterhooks|Thấp thỏm không yên',
      '乱七八糟|In a mess|Lộn xộn',
      '一路平安|Have a safe trip|Thượng lộ bình an',
      '万事如意|May all go well|Vạn sự như ý',
      '心想事成|May your wishes come true|Muốn gì được nấy',
      '九牛一毛|A drop in the ocean|Muối bỏ biển',
      '一心一意|Wholeheartedly|Một lòng một dạ',
      '百闻不如一见|Seeing is believing|Trăm nghe không bằng một thấy',
      '熟能生巧|Practice makes perfect|Có công mài sắt có ngày nên kim',
      '同舟共济|In the same boat|Cùng hội cùng thuyền',
      '一帆风顺|Smooth sailing|Thuận buồm xuôi gió',
    ],
    slang: [
      '牛|Awesome|Đỉnh / giỏi',
      '酷|Cool|Ngầu',
      '搞定|Done / sorted|Xong xuôi',
      '吐槽|To roast / complain|Than phiền / cà khịa',
      '点赞|To like (a post)|Thả like',
      '刷屏|To flood the feed|Spam / phủ sóng',
      '网红|Influencer|Người nổi tiếng trên mạng',
      '颜值|Looks|Nhan sắc',
      '学霸|Top student|Học bá',
      '吃货|Foodie|Tín đồ ăn uống',
      '土豪|Nouveau riche|Đại gia',
      '单身狗|Single person (joking)|Hội độc thân',
      '打卡|To check in (at a spot)|Check-in',
      '拉黑|To block (someone)|Chặn',
      '秒回|To reply instantly|Trả lời ngay lập tức',
    ],
  },
}
