import type { Category, Level } from './vocab'

// Second batch of vocabulary, appended after earlier lists so existing word IDs stay stable.
// Format: zh | English | Tiếng Việt
export const RAW_EXTRA_2: Record<Level, Partial<Record<Category, string[]>>> = {
  A1: {
    basics: [
      '白色|White|Màu trắng',
      '黑色|Black|Màu đen',
      '绿色|Green|Màu xanh lá',
      '黄色|Yellow|Màu vàng',
      '天|Day / sky|Ngày / trời',
      '半|Half|Một nửa',
      '两|Two (measure)|Hai',
      '第一|First|Thứ nhất',
      '每天|Every day|Mỗi ngày',
      '今年|This year|Năm nay',
      '去年|Last year|Năm ngoái',
      '明年|Next year|Năm sau',
      '上午|Morning (a.m.)|Buổi sáng',
      '下午|Afternoon|Buổi chiều',
      '晚安|Good night|Chúc ngủ ngon',
      '早安|Good morning|Chào buổi sáng',
      '对|Correct / right|Đúng',
      '错|Wrong|Sai',
      '一起|Together|Cùng nhau',
      '再|Again|Lại / nữa',
      '还|Still / also|Vẫn / còn',
      '只|Only|Chỉ',
      '太|Too (much)|Quá',
      '最|Most|Nhất',
      '真|Really / true|Thật',
      '每|Every|Mỗi',
      '个|General measure word|Cái / chiếc',
      '本|Measure word for books|Quyển',
      '张|Measure word for flat things|Tờ / tấm',
      '次|Time (occurrence)|Lần',
      '号|Number / date|Số / ngày',
      '岁|Years old|Tuổi',
      '喂|Hello (on the phone)|A lô',
      '吗|Question particle|Không? (trợ từ hỏi)',
      '呢|Particle (and you?)|Còn… thì sao?',
      '吧|Suggestion particle|Nhé / đi',
      '看见|To see|Nhìn thấy',
      '开|To open|Mở',
      '关|To close|Đóng / tắt',
      '进|To enter|Vào',
      '出|To exit|Ra',
      '住|To live (at)|Sống / ở',
      '站|To stand|Đứng',
    ],
    people: [
      '宝宝|Baby|Em bé',
      '大家|Everyone|Mọi người',
      '自己|Oneself|Bản thân / tự mình',
      '别人|Other people|Người khác',
      '小朋友|Kid|Bạn nhỏ',
      '老人|Elderly person|Người già',
      '年轻人|Young person|Người trẻ',
      '男孩|Boy|Cậu bé',
      '女孩|Girl|Cô bé',
      '校长|Principal|Hiệu trưởng',
    ],
    food: [
      '菜|Dish / vegetable|Món ăn / rau',
      '糖|Sugar / candy|Đường / kẹo',
      '盐|Salt|Muối',
      '葡萄|Grape|Nho',
      '橙子|Orange|Quả cam',
      '草莓|Strawberry|Dâu tây',
      '西红柿|Tomato|Cà chua',
      '土豆|Potato|Khoai tây',
      '冰淇淋|Ice cream|Kem',
      '巧克力|Chocolate|Sô-cô-la',
      '饼干|Biscuit|Bánh quy',
      '可乐|Cola|Cô-ca',
      '米|Rice (uncooked) / meter|Gạo / mét',
      '鸭子|Duck|Con vịt',
    ],
    travel: [
      '船|Boat|Thuyền',
      '票|Ticket|Vé',
      '门口|Entrance|Cửa ra vào',
      '东|East|Đông',
      '南|South|Nam',
      '西|West|Tây',
      '北|North|Bắc',
      '中间|Middle|Ở giữa',
      '旁边|Beside|Bên cạnh',
      '对面|Opposite|Đối diện',
    ],
    shopping: [
      '多少|How many / how much|Bao nhiêu',
      '一点儿|A little|Một chút',
      '大小|Size|Kích cỡ',
      '帽子|Hat|Mũ',
      '裤子|Trousers|Quần',
      '裙子|Skirt|Váy',
      '包|Bag|Túi',
      '毛|Ten cents (jiao)|Hào',
      '元|Yuan|Đồng tệ',
    ],
    feelings: [
      '好玩|Fun|Vui',
      '漂亮|Beautiful|Đẹp',
      '可爱|Cute|Dễ thương',
      '快乐|Happy|Vui vẻ',
      '不错|Not bad|Không tệ',
    ],
  },
  A2: {
    basics: [
      '以前|Before|Trước đây',
      '以后|After / later|Sau này',
      '刚才|Just now|Vừa nãy',
      '马上|Right away|Ngay lập tức',
      '一会儿|A moment|Một lát',
      '一样|Same|Giống nhau',
      '不同|Different|Khác nhau',
      '容易|Easy|Dễ',
      '难|Difficult|Khó',
      '干净|Clean|Sạch sẽ',
      '脏|Dirty|Bẩn',
      '安静|Quiet|Yên tĩnh',
      '热闹|Lively|Náo nhiệt',
      '长|Long|Dài',
      '短|Short|Ngắn',
      '高|Tall / high|Cao',
      '矮|Short (height)|Thấp',
      '胖|Fat|Béo',
      '瘦|Thin|Gầy',
      '离|Away from|Cách',
      '从|From|Từ',
      '向|Towards|Về phía',
      '比|Compared to|So với',
      '最近|Recently|Gần đây',
      '终于|Finally|Cuối cùng',
      '一般|Usually / ordinary|Bình thường',
      '特别|Especially|Đặc biệt',
      '非常|Extremely|Vô cùng',
      '帮忙|To help out|Giúp đỡ',
      '准备|To prepare|Chuẩn bị',
      '练习|To practice|Luyện tập',
      '复习|To review|Ôn tập',
      '考试|Exam|Kỳ thi',
      '作业|Homework|Bài tập',
      '班|Class|Lớp',
      '课|Lesson|Bài học',
      '词典|Dictionary|Từ điển',
      '句子|Sentence|Câu',
      '意思|Meaning|Ý nghĩa',
      '汉字|Chinese character|Chữ Hán',
    ],
    people: [
      '夫妻|Married couple|Vợ chồng',
      '父母|Parents|Bố mẹ',
      '亲戚|Relatives|Họ hàng',
      '外国人|Foreigner|Người nước ngoài',
      '主人|Host / owner|Chủ nhà',
      '运动员|Athlete|Vận động viên',
      '歌手|Singer|Ca sĩ',
      '演员|Actor|Diễn viên',
      '厨师|Chef|Đầu bếp',
      '老乡|Fellow townsman|Đồng hương',
      '室友|Roommate|Bạn cùng phòng',
    ],
    food: [
      '烤鸭|Roast duck|Vịt quay',
      '火锅|Hot pot|Lẩu',
      '豆腐|Tofu|Đậu phụ',
      '米粉|Rice noodles|Bún / phở',
      '炒饭|Fried rice|Cơm chiên',
      '烧烤|Barbecue|Đồ nướng',
      '零食|Snacks|Đồ ăn vặt',
      '酱油|Soy sauce|Xì dầu',
      '醋|Vinegar|Giấm',
      '辣椒|Chili|Ớt',
      '葱|Scallion|Hành lá',
      '大蒜|Garlic|Tỏi',
      '外卖|Takeout|Đồ ăn mang đi',
      '奶茶|Milk tea|Trà sữa',
      '矿泉水|Mineral water|Nước khoáng',
    ],
    travel: [
      '高铁|High-speed rail|Tàu cao tốc',
      '站台|Platform|Sân ga',
      '售票处|Ticket office|Quầy bán vé',
      '单程|One-way|Một chiều',
      '往返|Round trip|Khứ hồi',
      '路口|Intersection|Ngã tư',
      '红绿灯|Traffic light|Đèn giao thông',
      '过马路|To cross the road|Qua đường',
      '拐弯|To turn|Rẽ',
      '一直走|Go straight|Đi thẳng',
      '堵车|Traffic jam|Tắc đường',
      '海滩|Beach|Bãi biển',
      '寺庙|Temple|Chùa',
      '长城|Great Wall|Vạn Lý Trường Thành',
      '纪念品|Souvenir|Quà lưu niệm',
    ],
    shopping: [
      '颜色|Colour|Màu sắc',
      '便利店|Convenience store|Cửa hàng tiện lợi',
      '商场|Mall|Trung tâm thương mại',
      '购物车|Shopping cart|Giỏ hàng',
      '找钱|To give change|Thối tiền',
      '扫码|To scan a QR code|Quét mã',
      '支付宝|Alipay|Alipay',
      '讲价|To bargain|Mặc cả',
      '换货|To exchange goods|Đổi hàng',
      '新款|New style|Mẫu mới',
      '合适|Suitable / fits|Vừa / phù hợp',
      '袜子|Socks|Tất',
      '眼镜|Glasses|Kính',
    ],
    work: [
      '面试官|Interviewer|Người phỏng vấn',
      '实习|Internship|Thực tập',
      '工作日|Working day|Ngày làm việc',
      '打印|To print|In',
      '复印|To photocopy|Photo',
      '文件|Document|Tài liệu',
      '会议室|Meeting room|Phòng họp',
      '名片|Business card|Danh thiếp',
      '同意书|Consent form|Giấy đồng ý',
      '迟到|To be late|Đến muộn',
    ],
    tech: [
      '耳机|Headphones|Tai nghe',
      '充电器|Charger|Bộ sạc',
      '无线网|Wi-Fi|Wi-Fi',
      '信号|Signal|Tín hiệu',
      '游戏|Game|Trò chơi',
      '拍照|To take photos|Chụp ảnh',
      '打字|To type|Đánh máy',
      '关机|To shut down|Tắt máy',
      '开机|To power on|Bật máy',
      '二维码|QR code|Mã QR',
    ],
    feelings: [
      '放心|To be at ease|Yên tâm',
      '小心|Careful|Cẩn thận',
      '奇怪|Strange|Kỳ lạ',
      '有意思|Interesting|Thú vị',
      '难受|Uncomfortable|Khó chịu',
      '伤心|Sad / heartbroken|Đau lòng',
      '吃惊|Surprised|Ngạc nhiên',
      '轻松|Relaxed|Thoải mái',
    ],
    health: [
      '牙齿|Teeth|Răng',
      '耳朵|Ear|Tai',
      '鼻子|Nose|Mũi',
      '嘴|Mouth|Miệng',
      '腿|Leg|Chân',
      '胳膊|Arm|Cánh tay',
      '心脏|Heart|Tim',
      '流鼻涕|Runny nose|Sổ mũi',
      '挂号|To register (at hospital)|Lấy số khám',
      '药店|Pharmacy|Hiệu thuốc',
      '体温|Body temperature|Nhiệt độ cơ thể',
    ],
    slang: [
      '哈哈|Haha|Haha',
      '好的|OK|Được / OK',
      '对啊|Exactly|Đúng vậy',
      '算了|Forget it|Thôi bỏ đi',
      '厉害|Awesome / impressive|Giỏi quá',
      '不好意思|Excuse me / sorry|Ngại quá / xin lỗi',
    ],
  },
  B1: {
    basics: [
      '仍然|Still|Vẫn',
      '居然|Unexpectedly|Vậy mà',
      '几乎|Almost|Gần như',
      '大概|Probably / about|Khoảng / có lẽ',
      '到底|After all / on earth|Rốt cuộc',
      '完全|Completely|Hoàn toàn',
      '本来|Originally|Vốn dĩ',
      '按时|On time|Đúng giờ',
      '及时|Timely|Kịp thời',
      '确实|Indeed|Quả thực',
      '随时|At any time|Bất cứ lúc nào',
      '肯定|Certainly|Chắc chắn',
      '至于|As for|Còn về',
      '既然|Since (given that)|Đã… thì',
      '无论|No matter|Bất kể',
      '即使|Even if|Cho dù',
      '不管|Regardless|Dù / mặc kệ',
      '以为|To mistakenly think|Tưởng rằng',
      '认为|To think / believe|Cho rằng',
      '发现|To discover|Phát hiện',
      '发生|To happen|Xảy ra',
      '发展|To develop|Phát triển',
      '提高|To improve|Nâng cao',
      '保持|To maintain|Giữ gìn',
      '坚持|To persist|Kiên trì',
      '放弃|To give up|Từ bỏ',
      '选择|To choose|Lựa chọn',
      '适应|To adapt|Thích nghi',
      '理解|To understand|Hiểu',
      '表达|To express|Biểu đạt',
      '交流|To communicate|Giao lưu',
      '浪费|To waste|Lãng phí',
      '节约|To save / economize|Tiết kiệm',
      '允许|To allow|Cho phép',
      '禁止|To forbid|Cấm',
    ],
    people: [
      '性格|Personality|Tính cách',
      '态度|Attitude|Thái độ',
      '朋友圈|Social circle / Moments|Vòng bạn bè',
      '房东|Landlord|Chủ nhà trọ',
      '粉丝|Fans|Người hâm mộ',
      '陌生人|Stranger|Người lạ',
      '亲人|Family members|Người thân',
      '偶像|Idol|Thần tượng',
      '对象|Partner (romantic)|Người yêu / đối tượng',
      '独生子女|Only child|Con một',
    ],
    food: [
      '口味|Taste preference|Khẩu vị',
      '清淡|Light (flavor)|Thanh đạm',
      '油腻|Greasy|Nhiều dầu mỡ',
      '新鲜|Fresh|Tươi',
      '素食|Vegetarian food|Đồ chay',
      '海鲜|Seafood|Hải sản',
      '小吃|Street snack|Món ăn vặt',
      '菜谱|Recipe|Công thức nấu ăn',
      '蒸|To steam|Hấp',
      '煮|To boil|Luộc / nấu',
      '炒|To stir-fry|Xào',
      '烤|To roast / bake|Nướng',
      '打包|To pack (leftovers)|Gói mang về',
      '请客|To treat (someone)|Mời / đãi',
      'AA制|Go Dutch|Chia đều tiền',
    ],
    travel: [
      '攻略|Travel guide|Cẩm nang du lịch',
      '旅行社|Travel agency|Công ty du lịch',
      '名胜古迹|Historic sites|Danh lam thắng cảnh',
      '风俗|Custom|Phong tục',
      '民宿|Homestay|Nhà nghỉ homestay',
      '景区|Scenic area|Khu thắng cảnh',
      '转机|To transfer flights|Quá cảnh',
      '托运|To check baggage|Ký gửi hành lý',
      '安检|Security check|Kiểm tra an ninh',
      '时差|Jet lag / time difference|Chênh lệch múi giờ',
      '晕车|Carsick|Say xe',
      '自驾游|Road trip|Du lịch tự lái',
    ],
    shopping: [
      '促销|Promotion|Khuyến mãi',
      '满减|Spend-and-save discount|Giảm khi mua đủ',
      '包邮|Free shipping|Miễn phí vận chuyển',
      '售后|After-sales service|Hậu mãi',
      '保修|Warranty|Bảo hành',
      '评价|Review / to evaluate|Đánh giá',
      '退款|Refund|Hoàn tiền',
      '库存|Stock|Hàng tồn kho',
      '正品|Genuine product|Hàng chính hãng',
      '假货|Fake goods|Hàng giả',
      '优惠券|Coupon|Phiếu giảm giá',
    ],
    work: [
      '简报|Briefing|Bản tóm tắt',
      '日程|Schedule|Lịch trình',
      '加薪|Pay raise|Tăng lương',
      '奖金|Bonus|Tiền thưởng',
      '团队|Team|Đội nhóm',
      '分工|Division of labour|Phân công',
      '汇报|To report (to superiors)|Báo cáo',
      '反馈|Feedback|Phản hồi',
      '远程办公|Remote work|Làm việc từ xa',
      '试用期|Probation period|Thời gian thử việc',
      '年假|Annual leave|Nghỉ phép năm',
    ],
    tech: [
      '应用程序|Application|Ứng dụng',
      '平台|Platform|Nền tảng',
      '直播|Livestream|Phát trực tiếp',
      '短视频|Short video|Video ngắn',
      '流量|Data / traffic|Lưu lượng',
      '存储|Storage|Lưu trữ',
      '备份|Backup|Sao lưu',
      '病毒|Virus|Virus',
      '黑客|Hacker|Tin tặc',
      '升级|To upgrade|Nâng cấp',
      '卸载|To uninstall|Gỡ cài đặt',
    ],
    feelings: [
      '感激|Grateful|Biết ơn',
      '烦恼|Worry / vexation|Phiền não',
      '寂寞|Lonely|Cô đơn',
      '温暖|Warm|Ấm áp',
      '浪漫|Romantic|Lãng mạn',
      '尴尬|Awkward|Ngượng ngùng',
      '舍不得|Hate to part with|Không nỡ',
      '想念|To miss (someone)|Nhớ',
      '失眠|Insomnia|Mất ngủ',
    ],
    health: [
      '血压|Blood pressure|Huyết áp',
      '体检|Health checkup|Khám sức khỏe',
      '处方|Prescription|Đơn thuốc',
      '副作用|Side effect|Tác dụng phụ',
      '急诊|Emergency room|Cấp cứu',
      '中医|Traditional Chinese medicine|Đông y',
      '西医|Western medicine|Tây y',
      '拉肚子|Diarrhea|Tiêu chảy',
      '熬夜|To stay up late|Thức khuya',
      '运动量|Amount of exercise|Lượng vận động',
    ],
    society: [
      '社区|Community|Cộng đồng',
      '公民|Citizen|Công dân',
      '选举|Election|Bầu cử',
      '慈善|Charity|Từ thiện',
      '捐款|To donate money|Quyên góp',
      '环保|Environmental protection|Bảo vệ môi trường',
      '节能|Energy saving|Tiết kiệm năng lượng',
      '房价|Housing prices|Giá nhà',
      '租房|To rent a home|Thuê nhà',
      '代沟|Generation gap|Khoảng cách thế hệ',
      '婚礼|Wedding|Đám cưới',
    ],
    idiom: [
      '一举一动|Every move|Mọi cử chỉ',
      '自言自语|To talk to oneself|Lẩm bẩm một mình',
      '半信半疑|Half-believing|Bán tín bán nghi',
      '大吃一惊|Greatly surprised|Giật nảy mình',
      '五颜六色|Colourful|Đủ màu sắc',
      '十全十美|Perfect|Thập toàn thập mỹ',
      '一模一样|Exactly alike|Giống hệt nhau',
      '不知不觉|Unconsciously|Lúc nào không hay',
    ],
    slang: [
      '小case|A piece of cake|Chuyện nhỏ',
      '没戏|No chance|Hết hy vọng',
      '靠|Damn (mild)|Trời ơi',
      '666|Awesome (gaming)|Đỉnh quá',
      '我去|Whoa / no way|Trời đất',
      '有钱任性|Rich and carefree|Có tiền thì muốn làm gì thì làm',
    ],
  },
  B2: {
    basics: [
      '相对|Relatively|Tương đối',
      '普遍|Widespread|Phổ biến',
      '明显|Obvious|Rõ ràng',
      '具体|Specific|Cụ thể',
      '基本|Basic|Cơ bản',
      '主要|Main|Chủ yếu',
      '严重|Serious|Nghiêm trọng',
      '积极|Positive / active|Tích cực',
      '消极|Negative / passive|Tiêu cực',
      '合理|Reasonable|Hợp lý',
      '必要|Necessary|Cần thiết',
      '优势|Advantage|Ưu thế',
      '劣势|Disadvantage|Bất lợi',
      '前提|Premise|Tiền đề',
      '因素|Factor|Nhân tố',
      '现象|Phenomenon|Hiện tượng',
      '本质|Essence|Bản chất',
      '概念|Concept|Khái niệm',
      '逻辑|Logic|Logic',
      '假设|Hypothesis|Giả thuyết',
      '证明|To prove|Chứng minh',
      '强调|To emphasize|Nhấn mạnh',
      '促进|To promote|Thúc đẩy',
      '避免|To avoid|Tránh',
      '面临|To face|Đối mặt',
      '承担|To bear / undertake|Gánh vác',
      '实现|To realize|Thực hiện',
      '采取|To adopt (measures)|Áp dụng',
      '引起|To cause|Gây ra',
      '体现|To embody|Thể hiện',
    ],
    people: [
      '专家|Expert|Chuyên gia',
      '学者|Scholar|Học giả',
      '创业者|Entrepreneur|Người khởi nghiệp',
      '消费群体|Consumer group|Nhóm người tiêu dùng',
      '中产阶级|Middle class|Tầng lớp trung lưu',
      '上班族|Office workers|Dân công sở',
      '留学生|International student|Du học sinh',
      '退休人员|Retiree|Người nghỉ hưu',
      '代言人|Spokesperson|Người đại diện',
    ],
    food: [
      '食品安全|Food safety|An toàn thực phẩm',
      '有机|Organic|Hữu cơ',
      '添加剂|Additive|Chất phụ gia',
      '热量|Calories|Calo',
      '蛋白质|Protein|Chất đạm',
      '维生素|Vitamin|Vitamin',
      '膳食|Diet / meals|Chế độ ăn',
      '八大菜系|Eight great cuisines|Tám trường phái ẩm thực',
      '色香味|Colour, aroma and taste|Sắc hương vị',
    ],
    travel: [
      '签证申请|Visa application|Xin thị thực',
      '免签|Visa-free|Miễn thị thực',
      '出入境|Entry and exit|Xuất nhập cảnh',
      '旅游旺季|Peak season|Mùa cao điểm du lịch',
      '淡季|Off-season|Mùa thấp điểm',
      '文化遗产|Cultural heritage|Di sản văn hóa',
      '生态旅游|Ecotourism|Du lịch sinh thái',
      '跟团游|Group tour|Du lịch theo đoàn',
    ],
    shopping: [
      '电商|E-commerce|Thương mại điện tử',
      '直播带货|Livestream selling|Bán hàng qua livestream',
      '双十一|Singles’ Day (11.11)|Ngày lễ độc thân 11/11',
      '会员|Member|Hội viên',
      '积分|Points|Điểm tích lũy',
      '分期付款|Installment payment|Trả góp',
      '比价|To compare prices|So sánh giá',
      '剁手|To stop overspending (joke)|Chặt tay (vì mua sắm quá tay)',
    ],
    work: [
      '人力资源|Human resources|Nhân sự',
      '职场|Workplace|Chốn công sở',
      '跨部门|Cross-department|Liên phòng ban',
      '指标|Target / indicator|Chỉ tiêu',
      '效益|Benefit / returns|Hiệu quả kinh tế',
      '流程|Process|Quy trình',
      '规章制度|Rules and regulations|Nội quy',
      '考核|Assessment|Đánh giá, sát hạch',
      '外包|Outsourcing|Thuê ngoài',
      '裁员|Layoff|Cắt giảm nhân sự',
      '猎头|Headhunter|Săn đầu người',
    ],
    tech: [
      '虚拟现实|Virtual reality|Thực tế ảo',
      '物联网|Internet of Things|Internet vạn vật',
      '芯片|Chip|Chip',
      '自动化|Automation|Tự động hóa',
      '机器人|Robot|Robot',
      '电动车|Electric vehicle|Xe điện',
      '无人驾驶|Self-driving|Xe tự lái',
      '加密|Encryption|Mã hóa',
      '开源|Open source|Mã nguồn mở',
      '人脸识别|Face recognition|Nhận diện khuôn mặt',
    ],
    feelings: [
      '同情|Sympathy|Thông cảm',
      '敬佩|Admiration|Kính phục',
      '无奈|Helpless|Bất lực',
      '迷茫|Confused / lost|Mơ hồ, lạc lối',
      '矛盾心理|Ambivalence|Tâm lý mâu thuẫn',
      '满足感|Sense of fulfillment|Cảm giác thỏa mãn',
      '归属感|Sense of belonging|Cảm giác thuộc về',
      '安全感|Sense of security|Cảm giác an toàn',
    ],
    health: [
      '肥胖|Obesity|Béo phì',
      '抑郁症|Depression|Trầm cảm',
      '传染病|Infectious disease|Bệnh truyền nhiễm',
      '医疗保险|Medical insurance|Bảo hiểm y tế',
      '作息|Daily routine|Giờ giấc sinh hoạt',
      '久坐|Prolonged sitting|Ngồi lâu',
      '体质|Physique / constitution|Thể trạng',
      '保健品|Health supplement|Thực phẩm chức năng',
    ],
    society: [
      '少子化|Declining birth rate|Tỷ lệ sinh giảm',
      '独居|Living alone|Sống một mình',
      '基础设施|Infrastructure|Cơ sở hạ tầng',
      '公共交通|Public transport|Giao thông công cộng',
      '碳排放|Carbon emissions|Khí thải carbon',
      '新能源|New energy|Năng lượng mới',
      '城市规划|Urban planning|Quy hoạch đô thị',
      '性别平等|Gender equality|Bình đẳng giới',
      '公益|Public welfare|Công ích',
      '谣言|Rumour|Tin đồn',
    ],
    idiom: [
      '一石二鸟|Two birds with one stone|Một mũi tên trúng hai đích',
      '有目共睹|Obvious to all|Ai cũng thấy rõ',
      '津津有味|With relish|Ngon lành / say sưa',
      '各种各样|All kinds|Đủ loại',
      '想方设法|To try every means|Tìm mọi cách',
      '实事求是|Seek truth from facts|Thực sự cầu thị',
      '一干二净|Completely|Sạch trơn',
      '恍然大悟|Sudden realization|Bừng tỉnh ngộ ra',
    ],
    slang: [
      '凡尔赛|Humblebrag|Khoe khéo',
      '打call|To cheer for|Cổ vũ',
      '杠精|Contrarian / troll|Kẻ thích cãi',
      '柠檬精|Jealous person (joke)|Người hay ghen tị',
      '安利|To recommend enthusiastically|Giới thiệu nhiệt tình',
      '割韭菜|To fleece small investors|Cắt hẹ (lừa nhà đầu tư nhỏ)',
    ],
  },
  C1: {
    basics: [
      '与其|Rather than|Thà… còn hơn',
      '宁可|Would rather|Thà rằng',
      '以免|So as to avoid|Để tránh',
      '固然|Admittedly|Tất nhiên là',
      '况且|Moreover|Huống hồ',
      '倘若|If / supposing|Giả sử',
      '一旦|Once|Một khi',
      '反之|Conversely|Ngược lại',
      '据悉|It is reported|Được biết',
      '亦即|That is|Tức là',
      '鲜明|Distinct|Rõ nét',
      '深刻|Profound|Sâu sắc',
      '广泛|Extensive|Rộng rãi',
      '显著|Remarkable|Đáng kể',
      '迫切|Urgent|Cấp bách',
      '潜在|Potential|Tiềm ẩn',
      '根本|Fundamental|Căn bản',
      '机制|Mechanism|Cơ chế',
      '框架|Framework|Khung',
      '维度|Dimension|Chiều kích',
      '内涵|Connotation|Nội hàm',
      '阐述|To elaborate|Trình bày',
      '论证|To argue / demonstrate|Lập luận',
      '归纳|To summarize / induce|Quy nạp',
      '推断|To infer|Suy luận',
      '衡量|To weigh / measure|Đo lường, cân nhắc',
      '遏制|To curb|Kiềm chế',
      '凸显|To highlight|Làm nổi bật',
      '彰显|To manifest|Thể hiện rõ',
      '颠覆|To subvert|Lật đổ / phá vỡ',
    ],
    people: [
      '决策者|Decision-maker|Người ra quyết định',
      '利益相关者|Stakeholder|Bên liên quan',
      '先驱|Pioneer|Người tiên phong',
      '知识分子|Intellectual|Trí thức',
      '精英|Elite|Tinh hoa',
      '草根|Grassroots|Tầng lớp bình dân',
    ],
    work: [
      '供应链|Supply chain|Chuỗi cung ứng',
      '并购|Merger and acquisition|Sáp nhập và mua lại',
      '估值|Valuation|Định giá',
      '融资|Financing|Huy động vốn',
      '上市|To go public|Niêm yết',
      '垄断|Monopoly|Độc quyền',
      '风投|Venture capital|Đầu tư mạo hiểm',
      '商业模式|Business model|Mô hình kinh doanh',
      '可扩展性|Scalability|Khả năng mở rộng',
      '品牌形象|Brand image|Hình ảnh thương hiệu',
    ],
    tech: [
      '大模型|Large model (AI)|Mô hình lớn',
      '生成式|Generative|Tạo sinh',
      '神经网络|Neural network|Mạng nơ-ron',
      '算力|Computing power|Năng lực tính toán',
      '量子计算|Quantum computing|Điện toán lượng tử',
      '数字鸿沟|Digital divide|Khoảng cách số',
      '信息茧房|Filter bubble|Buồng kén thông tin',
      '元宇宙|Metaverse|Vũ trụ ảo',
    ],
    feelings: [
      '百感交集|Mixed feelings|Trăm mối cảm xúc',
      '心有余悸|Lingering fear|Vẫn còn sợ hãi',
      '刻骨铭心|Unforgettable|Khắc cốt ghi tâm',
      '悲喜交加|Mixed joy and sorrow|Buồn vui lẫn lộn',
      '如释重负|As if relieved of a burden|Như trút được gánh nặng',
      '无所适从|At a loss|Không biết làm theo ai',
    ],
    health: [
      '公共卫生|Public health|Y tế công cộng',
      '基因|Gene|Gen',
      '精准医疗|Precision medicine|Y học chính xác',
      '心理咨询|Counselling|Tư vấn tâm lý',
      '职业倦怠|Burnout|Kiệt sức nghề nghiệp',
    ],
    society: [
      '社会分层|Social stratification|Phân tầng xã hội',
      '阶层固化|Class rigidity|Sự cố định giai tầng',
      '贫富差距|Wealth gap|Khoảng cách giàu nghèo',
      '舆情|Public sentiment|Dư luận xã hội',
      '治理|Governance|Quản trị',
      '透明度|Transparency|Tính minh bạch',
      '问责|Accountability|Truy trách nhiệm',
      '可再生能源|Renewable energy|Năng lượng tái tạo',
      '碳中和|Carbon neutrality|Trung hòa carbon',
      '人口红利|Demographic dividend|Lợi tức dân số',
    ],
    idiom: [
      '见仁见智|Opinions differ|Mỗi người một ý',
      '众所周知|As everyone knows|Ai cũng biết',
      '相辅相成|Complement each other|Bổ trợ lẫn nhau',
      '息息相关|Closely related|Liên quan mật thiết',
      '层出不穷|Emerging endlessly|Xuất hiện liên tục',
      '日新月异|Changing rapidly|Thay đổi từng ngày',
      '供不应求|Demand exceeds supply|Cung không đủ cầu',
      '因人而异|Varies by person|Tùy người',
      '循序渐进|Step by step|Tuần tự tiến lên',
      '推陈出新|Weed through the old to bring forth the new|Bỏ cũ thay mới',
    ],
  },
  Native: {
    idiom: [
      '班门弄斧|To show off before an expert|Múa rìu qua mắt thợ',
      '叶公好龙|Professed love of what one fears|Diệp Công thích rồng',
      '纸上谈兵|Armchair strategy|Bàn binh trên giấy',
      '望梅止渴|Comfort oneself with illusions|Nhìn mơ đỡ khát',
      '杯弓蛇影|Paranoid suspicion|Thấy bóng cung tưởng rắn',
      '朝三暮四|Fickle|Sáng ba chiều bốn',
      '指鹿为马|Call a deer a horse|Chỉ hươu nói ngựa',
      '卧薪尝胆|Endure hardship for revenge|Nằm gai nếm mật',
      '负荆请罪|To offer a humble apology|Mang roi xin tội',
      '破釜沉舟|Burn one’s boats|Đập nồi dìm thuyền',
      '四面楚歌|Besieged on all sides|Tứ bề thọ địch',
      '完璧归赵|Return something intact|Trả ngọc về Triệu',
      '鹤立鸡群|Stand out from the crowd|Hạc giữa bầy gà',
      '对症下药|Prescribe the right remedy|Bốc thuốc đúng bệnh',
      '亡羊得牛|Lose small, gain big|Mất dê được bò',
      '一叶知秋|A small sign reveals the big picture|Một lá rơi biết thu sang',
      '口是心非|Say one thing, mean another|Khẩu thị tâm phi',
      '入木三分|Penetrating / incisive|Sâu sắc thấu đáo',
      '滴水穿石|Constant drops wear the stone|Nước chảy đá mòn',
      '近朱者赤|You are shaped by your company|Gần mực thì đen',
      '千里之行始于足下|A journey of a thousand miles begins with one step|Hành trình vạn dặm bắt đầu từ một bước chân',
      '书山有路勤为径|Diligence is the path up the mountain of books|Núi sách có đường, chăm chỉ là lối',
      '有志者事竟成|Where there’s a will there’s a way|Có chí thì nên',
      '车到山前必有路|Things will work out|Xe đến chân núi ắt có đường',
      '不入虎穴焉得虎子|Nothing ventured, nothing gained|Không vào hang cọp sao bắt được cọp con',
    ],
    slang: [
      'yyds|GOAT (eternal god)|Đỉnh nhất mọi thời đại',
      '绝绝子|Absolutely amazing|Tuyệt cú mèo',
      '离谱|Ridiculous|Vô lý hết sức',
      '上头|Hooked / obsessed|Nghiện / mê mẩn',
      '整活|To pull a stunt|Bày trò',
      '摆烂|To give up trying|Buông xuôi',
      'emo|Feeling down|Buồn bã / emo',
      '社牛|Social butterfly|Người siêu hướng ngoại',
      '破大防|Totally emotionally broken|Vỡ òa phòng tuyến',
      '栓Q|Thank you (ironic)|Cảm ơn (mỉa mai)',
      '拿捏|To have it under control|Nắm thóp / làm chủ',
      '嘴替|Someone who says what you think|Người nói hộ lòng mình',
      '搭子|Activity buddy|Bạn đồng hành (theo hoạt động)',
      '显眼包|Attention-seeker|Người thích gây chú ý',
      '特种兵旅游|Speed-run tourism|Du lịch kiểu đặc công',
      '泰酷辣|So cool|Ngầu quá',
      '尊嘟假嘟|Really or not? (cute)|Thật hay giả (dễ thương)',
      '主打一个|Main vibe is…|Chủ yếu là…',
      '电子榨菜|Background video while eating|“Dưa muối điện tử” (video xem khi ăn)',
      '情绪价值|Emotional value|Giá trị cảm xúc',
      '松弛感|Sense of ease|Cảm giác thong dong',
      '发疯文学|Unhinged-rant writing|Văn học phát điên',
      '卷王|Ultra-competitive person|Vua cạnh tranh',
      '养生朋克|Health-conscious punk|Dưỡng sinh kiểu punk',
      '打酱油|Just passing by|Chỉ đi ngang qua',
      '围观|To gather and watch|Hóng / vây xem',
      '躺赢|To win effortlessly|Nằm cũng thắng',
      '翻车|To fail publicly|Lật xe / thất bại',
      '真的会谢|Seriously, thanks a lot (ironic)|Thật sự cạn lời',
      '退退退|Go away (bad luck)|Lùi lùi lùi',
    ],
    society: [
      '鸡娃|Pushy parenting|Nuôi con kiểu gà chọi',
      '断舍离|Decluttering|Buông bỏ đồ đạc',
      '慢生活|Slow living|Sống chậm',
      '数字游民|Digital nomad|Du mục kỹ thuật số',
      '银发经济|Silver economy|Kinh tế bạc',
      '国潮|China-chic trend|Trào lưu Quốc triều',
      '996|9am–9pm, 6 days a week|Làm việc 996',
      '小镇做题家|Small-town exam grinder|Người luyện đề từ thị trấn nhỏ',
      '全职儿女|Full-time children|Con cái toàn thời gian',
      '轻断食|Intermittent fasting|Nhịn ăn gián đoạn',
    ],
  },
}
